"""cria tabela de contas a pagar e receber

Revision ID: 12af7eb441dc
Revises: 
Create Date: 2024-09-15 19:39:32.456779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12af7eb441dc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contas_a_pagar_e_receber',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('descricao', sa.String(length=30), nullable=True),
    sa.Column('valor', sa.Numeric(), nullable=True),
    sa.Column('tipo', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contas_a_pagar_e_receber')
    # ### end Alembic commands ###
